location ^~ /r2/ {
    resolver 1.1.1.1 8.8.8.8 valid=300s;
    resolver_timeout 5s;

    proxy_pass https://r2.dan.tw/;
    proxy_set_header Host r2.dan.tw;
    proxy_ssl_server_name on;
    proxy_ssl_name r2.dan.tw;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_http_version 1.1;
    proxy_set_header Accept-Encoding "";
    
    # 圖片快取設定
    expires 30d;
    add_header Cache-Control "public, max-age=2592000, immutable";
    
    # 允許 CORS 以利本地端 Canvas 或 Fancybox 下載處理
    add_header Access-Control-Allow-Origin "*";
    
    # 稍微放寬防盜連，允許 localhost 和 ztmr.club
    valid_referers none blocked server_names *.ztmr.club ztmr.club localhost 127.0.0.1;
    if ($invalid_referer) {
        return 403;
    }
}
